"""GENERATED by validation/derive_crop_seasons.py - do not edit by hand.
Observed growing seasons per crop: DES area-by-season, 2005-2014, eligible if >= 5% of assigned area.
"""
MIN_SHARE = 0.05
SOURCE = "Directorate of Economics & Statistics area by season (2005-2014), via the Kaggle 'Crop Production in India' mirror"
GROWING_SEASONS = {
  "wheat": {
    "seasons": [
      "rabi"
    ],
    "primary": "rabi",
    "area_share": {
      "kharif": 0.0,
      "rabi": 0.9999,
      "zaid": 0.0001
    },
    "mean_assigned_ha_per_year": 25652145
  },
  "rice_paddy": {
    "seasons": [
      "kharif",
      "zaid"
    ],
    "primary": "kharif",
    "area_share": {
      "kharif": 0.884,
      "rabi": 0.0348,
      "zaid": 0.0812
    },
    "mean_assigned_ha_per_year": 41980907
  },
  "bajra_pearl_millet": {
    "seasons": [
      "kharif"
    ],
    "primary": "kharif",
    "area_share": {
      "kharif": 0.9675,
      "rabi": 0.0024,
      "zaid": 0.0301
    },
    "mean_assigned_ha_per_year": 6580353
  },
  "jowar_sorghum": {
    "seasons": [
      "kharif",
      "rabi"
    ],
    "primary": "rabi",
    "area_share": {
      "kharif": 0.3919,
      "rabi": 0.6071,
      "zaid": 0.001
    },
    "mean_assigned_ha_per_year": 5838905
  },
  "maize": {
    "seasons": [
      "kharif",
      "rabi"
    ],
    "primary": "kharif",
    "area_share": {
      "kharif": 0.8386,
      "rabi": 0.1181,
      "zaid": 0.0433
    },
    "mean_assigned_ha_per_year": 6845629
  },
  "barley": {
    "seasons": [
      "kharif",
      "rabi"
    ],
    "primary": "rabi",
    "area_share": {
      "kharif": 0.0502,
      "rabi": 0.9498,
      "zaid": 0.0
    },
    "mean_assigned_ha_per_year": 482327
  },
  "gram_chickpea": {
    "seasons": [
      "rabi"
    ],
    "primary": "rabi",
    "area_share": {
      "kharif": 0.0038,
      "rabi": 0.9962,
      "zaid": 0.0
    },
    "mean_assigned_ha_per_year": 6511696
  },
  "mustard": {
    "seasons": [
      "rabi"
    ],
    "primary": "rabi",
    "area_share": {
      "kharif": 0.0035,
      "rabi": 0.9965,
      "zaid": 0.0
    },
    "mean_assigned_ha_per_year": 4446373
  },
  "groundnut": {
    "seasons": [
      "kharif",
      "rabi",
      "zaid"
    ],
    "primary": "kharif",
    "area_share": {
      "kharif": 0.8535,
      "rabi": 0.0854,
      "zaid": 0.0611
    },
    "mean_assigned_ha_per_year": 4785187
  },
  "soybean": {
    "seasons": [
      "kharif"
    ],
    "primary": "kharif",
    "area_share": {
      "kharif": 1.0,
      "rabi": 0.0,
      "zaid": 0.0
    },
    "mean_assigned_ha_per_year": 7955563
  },
  "cotton": {
    "seasons": [
      "kharif"
    ],
    "primary": "kharif",
    "area_share": {
      "kharif": 0.9945,
      "rabi": 0.0054,
      "zaid": 0.0001
    },
    "mean_assigned_ha_per_year": 8866790
  },
  "potato": {
    "seasons": [
      "kharif",
      "rabi"
    ],
    "primary": "rabi",
    "area_share": {
      "kharif": 0.0802,
      "rabi": 0.9153,
      "zaid": 0.0045
    },
    "mean_assigned_ha_per_year": 881818
  },
  "onion": {
    "seasons": [
      "kharif",
      "rabi",
      "zaid"
    ],
    "primary": "kharif",
    "area_share": {
      "kharif": 0.6815,
      "rabi": 0.2551,
      "zaid": 0.0634
    },
    "mean_assigned_ha_per_year": 218224
  }
}
