"""
crop_requirements.py — agronomic requirement ranges per crop, used by
crop_suitability.py to score a location. Pure data, no GEE dependency.

PROVENANCE
----------
temp_c, water_mm, ph and the texture classes are taken directly from the FAO
EcoCrop database (Crop Ecological Requirements Database, FAO), read from the
public OpenCLIM/ecocrop mirror of EcoCrop_DB.csv, one row per crop (the row
used is recorded in each entry's "ecocrop" field: EcoPort code + scientific
name). They are generic global ranges for the species, NOT tuned to Indian
varieties or to a specific sowing window.

These fields are NOT from EcoCrop and are my own rough estimates — treat as
placeholders until checked against ICAR / state agri-university sources:
  oc_min_gkg, slope_max_pct, yield_q_per_ha, and the season assignment.
mandi_commodity strings must match Agmarknet exactly; a wrong string just
yields "price unavailable".

Field conventions
-----------------
season       : "kharif" (Jun-Oct), "rabi" (Nov-Mar), "perennial" (all year).
               Drives which months of climate are averaged for that crop.
temp_c       : (abs_min, opt_min, opt_max, abs_max) mean air temp, deg C.
water_mm     : (abs_min, opt_min, opt_max, abs_max) water supply, mm. The LOW
               side is "needs irrigation" (fixable); the HIGH side is
               waterlogging/disease (not fixable by the farmer).
ph           : (abs_min, opt_min, opt_max, abs_max) soil pH (H2O).
texture_good / texture_marginal : USDA texture class codes, mapped from
               EcoCrop's light/medium/heavy words (light = sand, loamy sand,
               sandy loam; medium = loam, silt loam, silt, sandy clay loam;
               heavy = clay, silty clay, sandy clay, clay loam, silty clay
               loam). TEXT = optimal, TEXTR = tolerable.
tags         : species-level attributes, NOT soil-derived predictions.
               "vitamin_c_rich" is a property of the fruit species, not
               something the soil produces.
verified     : True only means the EcoCrop-derived ranges above were read from
               the database; it does NOT cover oc_min/slope/yield estimates.
"""

from typing import Any, Dict, List

TEXTURE_NAMES: Dict[int, str] = {
    1: "Clay", 2: "Silty clay", 3: "Sandy clay", 4: "Clay loam",
    5: "Silty clay loam", 6: "Sandy clay loam", 7: "Loam", 8: "Silt loam",
    9: "Sandy loam", 10: "Silt", 11: "Loamy sand", 12: "Sand",
}

SEASON_MONTHS: Dict[str, List[int]] = {
    "kharif": [6, 7, 8, 9, 10],
    "rabi": [11, 12, 1, 2, 3],
    "zaid": [3, 4, 5, 6],      # summer / zaid: irrigated Mar-Jun crops (DES season convention)
    "perennial": list(range(1, 13)),
}

SOURCE = "FAO EcoCrop database (ranges); other fields are estimates"

CROPS: List[Dict[str, Any]] = [{'id': 'wheat',
  'name': 'Wheat',
  'name_hi': 'गेहूँ',
  'season': 'rabi',
  'temp_c': (5.0, 15.0, 23.0, 27.0),
  'water_mm': (300.0, 750.0, 900.0, 1600.0),
  'ph': (5.5, 6.0, 8.2, 9.3),  # was EcoCrop (5.5, 6.0, 7.0, 8.5); see ph_override_note
  'texture_good': (6, 7, 8, 10),
  'texture_marginal': (1, 2, 3, 4, 5),
  'oc_min_gkg': 6.0,
  'slope_max_pct': 8,
  'tags': ['cereal'],
  'yield_q_per_ha': 35,
  'mandi_commodity': 'Wheat',
  'notes': '',
  'ecocrop': {'code': 2114, 'scientific_name': 'Triticum aestivum'},
  'ph_override_note': 'EcoCrop wheat optimum pH 6.0-7.0 is a temperate range and scored normal Indo-Gangetic wheat soils low (pH ~7.8-8.2). Optimum upper bound set to 8.2, the pHs threshold above which ICAR-CSSRI classes Indian soils as sodic (cssri.res.in). Wheat is grown through that threshold with declining yield: ICAR-CSSRI Farmer FIRST trials in the sodic Ghaghar basin (Sustainability 2021, 13(6):3378) report wheat on soils of pH 8.25 to above 9.25, and an ICAR-NBPGR wheat panel study (PMC, GWAS) describes normal fertile Indian wheat soils at pH ~7.84. The 9.3 absolute maximum is an ESTIMATE (the >=9.25 sodicity class boundary in those trials). Verify against ICAR-IIWBR / CSSRI primary documents.',
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'rice_paddy',
  'name': 'Rice (paddy)',
  'name_hi': 'धान',
  'season': 'kharif',
  'temp_c': (16.0, 25.0, 35.0, 38.0),
  'water_mm': (1000.0, 1500.0, 2000.0, 4000.0),
  'ph': (3.5, 5.0, 8.0, 9.0),
  'texture_good': (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
  'texture_marginal': (),
  'oc_min_gkg': 8.0,
  'slope_max_pct': 3,
  'tags': ['cereal'],
  'yield_q_per_ha': 26,
  'mandi_commodity': 'Paddy(Dhan)(Common)',
  'notes': 'EcoCrop indica-subspecies row. Needs standing water; drains-too-fast soils are poor.',
  'excess_sensitivity': 'tolerant',  # paddy is cultivated under standing water, so high rainfall is not an excess-water hazard in the way it is for upland crops (e.g. grown at >3000 mm/yr on the Konkan and Kerala coasts)
  'ecocrop': {'code': 8143, 'scientific_name': 'Oryza sativa ssp. indica'},
  'slope_terraceable_pct': 30,
  'slope_override_note': 'Paddy is routinely grown on bench-terraced slopes: FAO bench-terrace guidance names level/irrigation terraces for rice on 12-47% slopes (fao.org/3/ad083e/AD083e07.htm); WOCAT documents rainfed paddy terraces on 30-60% slopes in the Philippine Cordillera. A GIS land-suitability study (IPB, Sukabumi) found irrigated rice yield fell from 5.16 to 2.70 t/ha from 0-3% to 30-45% slopes and called slopes >30% unsuitable even with terracing. So slopes above the natural limit are a terracing requirement (soft), and 30% is taken as the terraceable limit. The score at that limit (0.5) is an ESTIMATE.',
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'bajra_pearl_millet',
  'name': 'Bajra (pearl millet)',
  'name_hi': 'बाजरा',
  'season': 'kharif',
  'temp_c': (12.0, 25.0, 35.0, 40.0),
  'water_mm': (200.0, 400.0, 900.0, 1700.0),
  'ph': (4.5, 5.0, 8.0, 8.3),  # optimum ceiling widened 6.5->8.0: ICAR documents Rajasthan bajra thriving in alkaline soils (see ph_override_note below); absolute max kept at EcoCrop's 8.3
  'texture_good': (6, 7, 8, 9, 10, 11, 12),
  'texture_marginal': (),
  'oc_min_gkg': 3.0,
  'slope_max_pct': 10,
  'tags': ['millet', 'drought_tolerant'],
  'yield_q_per_ha': 13,
  'mandi_commodity': 'Bajra(Pearl Millet/Cumbu)',
  'notes': '',
  'ecocrop': {'code': 8418, 'scientific_name': 'Pennisetum glaucum', 'ph_override_note': 'Optimum pH ceiling raised from EcoCrop generic 6.5 to 8.0 based on ICAR (Central Arid Zone Research Institute / SKN College of Agriculture, Jobner) documentation of pearl millet performing well in Rajasthan alkaline soils; absolute max unchanged.'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'jowar_sorghum',
  'name': 'Jowar (sorghum)',
  'name_hi': 'ज्वार',
  'season': 'kharif',
  'temp_c': (8.0, 22.0, 35.0, 40.0),
  'water_mm': (300.0, 500.0, 800.0, 1200.0),  # was EcoCrop generic (300, 400, 600, 700). Optimum raised to 500-800 mm and absolute max to 1200 mm, see water_override_note
  'ph': (5.0, 5.5, 7.5, 8.0),
  'texture_good': (1, 2, 3, 4, 5, 6, 7, 8, 10),
  'texture_marginal': (9, 11, 12),
  'oc_min_gkg': 4.0,
  'slope_max_pct': 10,
  'tags': ['millet', 'drought_tolerant'],
  'yield_q_per_ha': 15,
  'mandi_commodity': 'Jowar(Sorghum)',
  'notes': '',
  'ecocrop': {'code': 48747, 'scientific_name': 'Sorghum bicolor', 'water_override_note': 'Kharif sorghum is the monsoon-season crop of India, so Jun-Oct rainfall at most sorghum districts exceeds the EcoCrop generic ceiling of 600-700 mm, which scored it ~0 almost everywhere (validation vs district sown-area statistics: 0 of 3 districts where jowar is a major crop were rated suitable). Optimum set to 500-800 mm per the ICRISAT/FAO sorghum production chapter (500-800 mm well distributed over the season is normally adequate; ET of a 110-130 day crop is 450-750 mm; sorghum tolerates waterlogging and can be grown in high-rainfall areas; oar.icrisat.org/6113). That source gives no numeric rainfall ceiling, so the 1200 mm absolute maximum is an ESTIMATE, to be refined against ICAR-IIMR / AICRP-Sorghum agro-climatic data.'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'maize',
  'name': 'Maize',
  'name_hi': 'मक्का',
  'season': 'kharif',
  'temp_c': (10.0, 18.0, 33.0, 47.0),
  'water_mm': (400.0, 600.0, 1200.0, 1800.0),
  'ph': (4.5, 5.0, 7.0, 8.5),
  'texture_good': (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
  'texture_marginal': (),
  'oc_min_gkg': 7.0,
  'slope_max_pct': 8,
  'tags': ['cereal'],
  'yield_q_per_ha': 30,
  'mandi_commodity': 'Maize',
  'notes': '',
  'ecocrop': {'code': 2175, 'scientific_name': 'Zea mays'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'barley',
  'name': 'Barley',
  'name_hi': 'जौ',
  'season': 'rabi',
  'temp_c': (2.0, 15.0, 20.0, 40.0),
  'water_mm': (200.0, 500.0, 1000.0, 2000.0),
  'ph': (6.0, 6.5, 7.5, 8.0),
  'texture_good': (6, 7, 8, 10),
  'texture_marginal': (1, 2, 3, 4, 5, 9, 11, 12),
  'oc_min_gkg': 4.0,
  'slope_max_pct': 8,
  'tags': ['cereal'],
  'yield_q_per_ha': 30,
  'mandi_commodity': 'Barley (Jau)',
  'notes': '',
  'ecocrop': {'code': 1232, 'scientific_name': 'Hordeum vulgare'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'gram_chickpea',
  'name': 'Gram (chickpea)',
  'name_hi': 'चना',
  'season': 'rabi',
  'temp_c': (7.0, 15.0, 29.0, 35.0),
  'water_mm': (300.0, 600.0, 1000.0, 1800.0),
  'ph': (4.7, 6.0, 8.5, 9.5),
  'texture_good': (1, 2, 3, 4, 5, 6, 7, 8, 10),
  'texture_marginal': (9, 11, 12),
  'oc_min_gkg': 5.0,
  'slope_max_pct': 8,
  'tags': ['pulse', 'protein_rich'],
  'yield_q_per_ha': 11,
  'mandi_commodity': 'Bengal Gram(Gram)(Whole)',
  'notes': '',
  'ecocrop': {'code': 2479, 'scientific_name': 'Cicer arietinum'},
  'humidity_sensitive': {'source': 'Chickpea does poorly in warm, humid environments (ECHO); ICRISAT chickpea guidance recommends the cool post-rainy season where the rains coincide with warm humid weather. NOTE van der Maessen (1972, FAO) found relative humidity had little influence on fruit setting, so the concern is disease pressure (wilt, blight, pod borer), not pollination. The generic EcoCrop temperature range (optimum 18-26 / 21-29 C in van der Maessen) was reviewed and is consistent, so it is unchanged. Secondary sources - verify against ICAR-IIPR documents.'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'mustard',
  'name': 'Mustard',
  'name_hi': 'सरसों',
  'season': 'rabi',
  'temp_c': (7.0, 15.0, 28.0, 40.0),
  'water_mm': (500.0, 700.0, 2400.0, 4200.0),
  'ph': (5.0, 5.5, 8.0, 9.0),  # optimum ceiling widened 6.5->8.0, abs max 8.0->9.0: ICAR documents mustard germplasm tolerant to pH 9.4 alkalinity, and Bharatpur hosts ICAR's national mustard research centre (see ph_override_note)
  'texture_good': (6, 7, 8, 10),
  'texture_marginal': (1, 2, 3, 4, 5, 9, 11, 12),
  'oc_min_gkg': 5.0,
  'slope_max_pct': 8,
  'tags': ['oilseed'],
  'yield_q_per_ha': 14,
  'mandi_commodity': 'Mustard',
  'notes': '',
  'ecocrop': {'code': 548, 'scientific_name': 'Brassica juncea', 'ph_override_note': 'Optimum pH ceiling raised from EcoCrop generic 6.5 to 8.0, absolute max 8.0 to 9.0, based on ICAR-documented Indian mustard (B. juncea) germplasm tolerant to alkalinity pH 9.4 (Singh & Sharma 2019, Indian J. Plant Genetic Resources) and mustard being a flagship crop of alkaline-soil Rajasthan, home to ICAR Directorate of Rapeseed-Mustard Research, Sewar, Bharatpur.'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'groundnut',
  'name': 'Groundnut',
  'name_hi': 'मूंगफली',
  'season': 'kharif',
  'temp_c': (10.0, 22.0, 32.0, 45.0),
  'water_mm': (400.0, 600.0, 1500.0, 4000.0),
  'ph': (4.5, 5.5, 7.5, 8.5),  # was EcoCrop (4.5, 5.5, 6.5, 8.5); see ph_override_note
  'texture_good': (6, 7, 8, 10),
  'texture_marginal': (1, 2, 3, 4, 5, 9, 11, 12),
  'oc_min_gkg': 5.0,
  'slope_max_pct': 8,
  'tags': ['oilseed', 'protein_rich'],
  'yield_q_per_ha': 18,
  'mandi_commodity': 'Groundnut',
  'notes': 'Loose, well-drained soil helps pod development.',
  'ecocrop': {'code': 2199, 'scientific_name': 'Arachis hypogaea'},
  'ph_override_note': 'Optimum upper bound raised from 6.5 to 7.5: Assam Agricultural University package of practices gives the desirable groundnut pH as 5.5-7.5. Absolute limits unchanged. Verify against ICAR-DGR / ICRISAT primary guidance.',
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'soybean',
  'name': 'Soybean',
  'name_hi': 'सोयाबीन',
  'season': 'kharif',
  'temp_c': (10.0, 20.0, 33.0, 38.0),
  'water_mm': (450.0, 600.0, 1500.0, 1800.0),
  'ph': (4.5, 5.5, 6.5, 8.4),
  'texture_good': (6, 7, 8, 10),
  'texture_marginal': (1, 2, 3, 4, 5, 9, 11, 12),
  'oc_min_gkg': 8.0,
  'slope_max_pct': 6,
  'tags': ['oilseed', 'protein_rich'],
  'yield_q_per_ha': 11,
  'mandi_commodity': 'Soyabean',
  'notes': '',
  'ecocrop': {'code': 1150, 'scientific_name': 'Glycine max'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'cotton',
  'name': 'Cotton',
  'name_hi': 'कपास',
  'season': 'kharif',
  'temp_c': (15.0, 22.0, 36.0, 42.0),
  'water_mm': (450.0, 750.0, 1200.0, 1500.0),
  'ph': (5.0, 6.0, 7.5, 9.5),
  'texture_good': (1, 2, 3, 4, 5, 6, 7, 8, 10),
  'texture_marginal': (9, 11, 12),
  'oc_min_gkg': 6.0,
  'slope_max_pct': 5,
  'tags': ['fibre'],
  'yield_q_per_ha': 15,
  'mandi_commodity': 'Cotton',
  'notes': '',
  'ecocrop': {'code': 1160, 'scientific_name': 'Gossypium hirsutum'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'sugarcane',
  'name': 'Sugarcane',
  'name_hi': 'गन्ना',
  'season': 'perennial',
  'temp_c': (15.0, 24.0, 37.0, 41.0),
  'water_mm': (1000.0, 1500.0, 2000.0, 5000.0),
  'ph': (4.5, 5.0, 8.0, 9.0),
  'texture_good': (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
  'texture_marginal': (),
  'oc_min_gkg': 8.0,
  'slope_max_pct': 4,
  'tags': ['cash_crop'],
  'yield_q_per_ha': 700,
  'mandi_commodity': None,
  'notes': 'High water demand; usually sold to mills, not via mandi.',
  'ecocrop': {'code': 1884, 'scientific_name': 'Saccharum officinarum'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'potato',
  'name': 'Potato',
  'name_hi': 'आलू',
  'season': 'rabi',
  'temp_c': (7.0, 15.0, 25.0, 30.0),
  'water_mm': (250.0, 500.0, 800.0, 2000.0),
  'ph': (4.2, 5.0, 6.2, 8.5),
  'texture_good': (6, 7, 8, 10),
  'texture_marginal': (1, 2, 3, 4, 5, 9, 11, 12),
  'oc_min_gkg': 8.0,
  'slope_max_pct': 6,
  'tags': ['vegetable'],
  'yield_q_per_ha': 220,
  'mandi_commodity': 'Potato',
  'notes': '',
  'ecocrop': {'code': 1971, 'scientific_name': 'Solanum tuberosum'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'onion',
  'name': 'Onion',
  'name_hi': 'प्याज',
  'season': 'rabi',
  'temp_c': (4.0, 12.0, 25.0, 30.0),
  'water_mm': (300.0, 350.0, 600.0, 2800.0),
  'ph': (4.3, 6.0, 7.0, 8.3),
  'texture_good': (6, 7, 8, 10),
  'texture_marginal': (1, 2, 3, 4, 5, 9, 11, 12),
  'oc_min_gkg': 7.0,
  'slope_max_pct': 6,
  'tags': ['vegetable'],
  'yield_q_per_ha': 250,
  'mandi_commodity': 'Onion',
  'notes': '',
  'ecocrop': {'code': 364, 'scientific_name': 'Allium cepa'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'lemon',
  'name': 'Lemon',
  'name_hi': 'नींबू',
  'season': 'perennial',
  'temp_c': (12.0, 15.0, 28.0, 36.0),
  'water_mm': (300.0, 1000.0, 2300.0, 4000.0),
  'ph': (5.5, 6.5, 7.0, 8.0),
  'texture_good': (6, 7, 8, 9, 10, 11, 12),
  'texture_marginal': (1, 2, 3, 4, 5),
  'oc_min_gkg': 8.0,
  'slope_max_pct': 15,
  'tags': ['fruit', 'vitamin_c_rich'],
  'yield_q_per_ha': 110,
  'mandi_commodity': 'Lemon',
  'notes': 'EcoCrop Citrus limon row. Sensitive to waterlogging and salinity; needs good drainage.',
  'ecocrop': {'code': 714, 'scientific_name': 'Citrus limon'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'guava',
  'name': 'Guava',
  'name_hi': 'अमरूद',
  'season': 'perennial',
  'temp_c': (10.0, 20.0, 33.0, 45.0),
  'water_mm': (400.0, 1000.0, 3000.0, 5000.0),
  'ph': (4.0, 5.5, 7.5, 8.5),
  'texture_good': (6, 7, 8, 10),
  'texture_marginal': (1, 2, 3, 4, 5, 9, 11, 12),
  'oc_min_gkg': 7.0,
  'slope_max_pct': 20,
  'tags': ['fruit', 'vitamin_c_rich'],
  'yield_q_per_ha': 120,
  'mandi_commodity': 'Guava',
  'notes': 'Hardy across many soils.',
  'ecocrop': {'code': 1804, 'scientific_name': 'Psidium guajava'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'amla_gooseberry',
  'name': 'Amla (gooseberry)',
  'name_hi': 'आंवला',
  'season': 'perennial',
  'temp_c': (14.0, 20.0, 29.0, 35.0),
  'water_mm': (700.0, 1500.0, 2500.0, 4200.0),
  'ph': (5.0, 6.0, 8.0, 8.5),
  'texture_good': (6, 7, 8, 10),
  'texture_marginal': (1, 2, 3, 4, 5, 9, 11, 12),
  'oc_min_gkg': 6.0,
  'slope_max_pct': 20,
  'tags': ['fruit', 'vitamin_c_rich', 'drought_tolerant'],
  'yield_q_per_ha': 100,
  'mandi_commodity': 'Amla(Nelli Kai)',
  'notes': 'EcoCrop lists it as Emblica officinalis (syn. Phyllanthus emblica).',
  'ecocrop': {'code': 8537, 'scientific_name': 'Emblica officinalis'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'mango',
  'name': 'Mango',
  'name_hi': 'आम',
  'season': 'perennial',
  'temp_c': (8.0, 24.0, 30.0, 48.0),
  'water_mm': (300.0, 600.0, 1500.0, 2600.0),
  'ph': (4.3, 5.5, 7.5, 8.5),
  'texture_good': (6, 7, 8, 9, 10, 11, 12),
  'texture_marginal': (1, 2, 3, 4, 5),
  'oc_min_gkg': 8.0,
  'slope_max_pct': 20,
  'tags': ['fruit'],
  'yield_q_per_ha': 90,
  'mandi_commodity': 'Mango',
  'notes': '',
  'ecocrop': {'code': 1416, 'scientific_name': 'Mangifera indica'},
  'rainfall_seasonality': {
    'months': [11, 12, 1, 2, 3],
    'source': 'Mango needs DRY weather around flowering / fruit set (Nov-Mar in India). Sources (secondary summaries - verify against primary NHB / ICAR-CISH documents): '
              'India National Horticulture Board guidance as summarised at agriculture.institute (timing and distribution of rainfall matter far more than annual total; '
              'a distinct 3-4 month dry season after the monsoon triggers flowering; rain/fog during flowering Nov-Feb causes poor fruit set and mildew); '
              'IJSDR 2506124 review (mango thrives at 75-375 cm/yr WITH a dry season; rain during flowering reduces fruit set).'},
  'source': 'FAO EcoCrop',
  'verified': True},
 {'id': 'avocado',
  'name': 'Avocado',
  'name_hi': 'एवोकाडो',
  'season': 'perennial',
  'temp_c': (10.0, 14.0, 40.0, 45.0),
  'water_mm': (300.0, 500.0, 2000.0, 2500.0),
  'ph': (4.5, 5.0, 5.8, 7.0),
  'texture_good': (6, 7, 8, 10),
  'texture_marginal': (),
  'oc_min_gkg': 12.0,
  'slope_max_pct': 25,
  'tags': ['fruit'],
  'yield_q_per_ha': None,
  'mandi_commodity': None,
  'notes': 'EcoCrop generic-species row. Very sensitive to waterlogging and alkaline soil; usually '
           'climate-limited in India outside hills/south.',
  'ecocrop': {'code': 1659, 'scientific_name': 'Persea americana'},
  'source': 'FAO EcoCrop',
  'verified': True}]

CROPS_BY_ID: Dict[str, Dict[str, Any]] = {c["id"]: c for c in CROPS}
