#!/usr/bin/env python3
"""
derive_crop_seasons.py - derive WHICH SEASONS each crop is actually grown in, from observed practice.

Source: Directorate of Economics & Statistics area-by-season (Kaggle 'Crop Production in India' mirror, 1997-2015; years 2005-2014 used).
Rule  : area is assigned to a growing season: Kharif + Autumn + Winter -> kharif (monsoon-sown; DES 'Autumn'/'Winter' are
        state-specific names for monsoon-sown rice such as aus/aman), Rabi -> rabi, Summer -> zaid. 'Whole Year' is unassigned and
        excluded from the shares. A season is ELIGIBLE for a crop if it holds >= MIN_SHARE of the crop's assigned area.
Output: backend/app/services/agri/crop_seasons.py  (generated; do not edit by hand - rerun this script)

Eligibility = where the crop is grown in practice (an upper bound that already reflects varieties, sowing windows and
photoperiod/vernalisation needs the engine does not model). Suitability within an eligible season is scored on physical evidence.
"""
import json
from pathlib import Path
import pandas as pd
from season_map import SEASON_MAP

HERE = Path(__file__).parent
CSV = HERE / "ground_truth/_download_cache/crop_production.csv"
OUT = HERE.parent / "backend/app/services/agri/crop_seasons.py"
Y0, Y1, MIN_SHARE = 2005, 2014, 0.05
CROPS = {"wheat": "Wheat", "rice_paddy": "Rice", "bajra_pearl_millet": "Bajra", "jowar_sorghum": "Jowar", "maize": "Maize",
         "barley": "Barley", "gram_chickpea": "Gram", "mustard": "Rapeseed &Mustard", "groundnut": "Groundnut",
         "soybean": "Soyabean", "cotton": "Cotton(lint)", "potato": "Potato", "onion": "Onion"}


def main():
    if not CSV.exists():
        raise SystemExit("run build_ground_truth.py first (it downloads the dataset)")
    df = pd.read_csv(CSV); df.columns = [c.strip() for c in df.columns]
    for c in ("Season", "Crop"): df[c] = df[c].astype(str).str.strip()
    df = df[df.Crop_Year.between(Y0, Y1) & (df.Area > 0)]
    df["s"] = df.Season.str.lower().map(SEASON_MAP)
    out = {}
    for cid, name in CROPS.items():
        g = df[(df.Crop == name) & df.s.notna()].groupby("s").Area.sum()
        tot = float(g.sum()); shares = {s: round(float(g.get(s, 0)) / tot, 4) for s in ("kharif", "rabi", "zaid")}
        ok = [s for s in ("kharif", "rabi", "zaid") if shares[s] >= MIN_SHARE]
        primary = max(shares, key=shares.get)
        out[cid] = {"seasons": ok, "primary": primary, "area_share": shares, "mean_assigned_ha_per_year": round(tot / (Y1 - Y0 + 1))}
    src = ('"""GENERATED by validation/derive_crop_seasons.py - do not edit by hand.\n'
           f'Observed growing seasons per crop: DES area-by-season, {Y0}-{Y1}, eligible if >= {MIN_SHARE:.0%} of assigned area.\n"""\n'
           f"MIN_SHARE = {MIN_SHARE}\nSOURCE = \"Directorate of Economics & Statistics area by season ({Y0}-{Y1}), via the Kaggle 'Crop Production in India' mirror\"\n"
           f"GROWING_SEASONS = {json.dumps(out, indent=2)}\n")
    OUT.write_text(src, encoding="utf-8"); print("wrote", OUT)
    for cid, v in out.items(): print(f"  {cid:20s} {v['seasons']}  primary={v['primary']}  shares={v['area_share']}")


if __name__ == "__main__":
    main()
